### ISSUE TITLE
Compatibility of stitchr with Windows

### ISSUE THREAD

**Issue by naity** [JamieHeather/stitchr#31] opened 2023-05-01 20:46 UTC
Hi @JamieHeather,

I'm trying to use `stitchr` on my Windows machine, but I'm encountering an error message that looks like this:

```
 C:\Users\user1>stitchr -v TRBV2-1 -j TRBJ2-1 -cdr3 CASSRLAGGMDEQFF
Traceback (most recent call last):
  File "C:\Users\user1\anaconda3\envs\ml\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user1\anaconda3\envs\ml\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user1\anaconda3\envs\ml\Scripts\stitchr.exe\__main__.py", line 7, in <module>
  File "C:\Users\user1\anaconda3\envs\ml\lib\site-packages\Scripts\stitchr.py", line 399, in main
    input_args, chain = fxn.sort_input(vars(args()))
  File "C:\Users\user1\anaconda3\envs\ml\lib\site-packages\Scripts\functions.py", line 161, in sort_input
    species_dirs = find_species_covered()
  File "C:\Users\user1\anaconda3\envs\ml\lib\site-packages\Scripts\functions.py", line 131, in find_species_covered
    species_list = [x for x in os.listdir(data_dir) if os.path.isdir(data_dir + '/' + x) and
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
```

I'm not sure if this error is caused by a compatibility issue between stitchr and Windows or if it's due to a different problem. Do you have any suggestions for how I might resolve this issue?

Thank you!

**Comment by JamieHeather** [comment] 2023-05-01 22:34
Hello hello,

Ahh this is a Windows-specific thing, as I only really use stitchr on Linux and OSX. However I think I know what the problem is (Windows using back- instead of forward-slashes for paths).

Before I try to fix that, does `stitchr -dd` work for you? If so could you let me know what path it gives.

**Comment by naity** [comment] 2023-05-02 00:05
Thank you for the prompt response. Unfortunately, `stitchr -dd` doesn't return anything.

I was also wondering if it would be possible to `import stitchr` and use it in a Python script or Jupyter Notebook. Thanks again!

**Comment by JamieHeather** [comment] 2023-05-03 23:46
Fixed in [e2d7895](https://github.com/JamieHeather/stitchr/commit/e2d78959bf7873172fb8cb825a3027fdd86c037b), v1.1.2, tested on Ubuntu/Mac OSX/Windows.

This also fixes importing stitchr to use in other scripts, which got broken in the conversion to a package. I wrote a quick synopsis of how to start doing so at https://jamieheather.github.io/stitchr/importing.html

The changes have been pushed to PyPI, so you should be able to upgrade or re-download with pip to get the changes.

**Closed by JamieHeather** 2023-05-03 23:46 UTC
Labels: bug, enhancement

**Comment by naity** [comment] 2023-05-04 19:11
Awesome, thank you @JamieHeather!

I was wondering if it is possible to use `stitchr` for BCRs?

**Comment by JamieHeather** [comment] 2023-05-04 19:56
You're very welcome - it was something I needed to get to sooner or later anyway!

So in theory yes it absolutely can be used for BCRs, which we demonstrate in the paper (and which [has a section in the docs](https://jamieheather.github.io/stitchr/immunoglobulins.html). However as everything is much more complicated in BCRs (and me not being a BCR expert) this isn't something that I'm able to fully support as I can with TCRs. 

Generally speaking, what with greater levels of germline polymorphism and SHM I'd recommend using longer reads with the seamless option, and/or ensuring coverage of the relevant genes via the additional genes file. Either way when working with BCRs you might end up having to get under the hood a bit more. Happy to chat about specific use cases if the guidance in the docs isn't enough.
